# CMake generated Testfile for 
# Source directory: /Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/App/Tests
# Build directory: /Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/build-tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[calc_engine]=] "/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/build-tests/test_calc_engine")
set_tests_properties([=[calc_engine]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/App/Tests/CMakeLists.txt;325;add_test;/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/App/Tests/CMakeLists.txt;0;")
add_test([=[expr_util]=] "/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/build-tests/test_expr_util")
set_tests_properties([=[expr_util]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/App/Tests/CMakeLists.txt;326;add_test;/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/App/Tests/CMakeLists.txt;0;")
add_test([=[expr_buffer]=] "/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/build-tests/test_expr_buffer")
set_tests_properties([=[expr_buffer]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/App/Tests/CMakeLists.txt;327;add_test;/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/App/Tests/CMakeLists.txt;0;")
add_test([=[persist_roundtrip]=] "/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/build-tests/test_persist_roundtrip")
set_tests_properties([=[persist_roundtrip]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/App/Tests/CMakeLists.txt;328;add_test;/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/App/Tests/CMakeLists.txt;0;")
add_test([=[prgm_exec]=] "/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/build-tests/test_prgm_exec")
set_tests_properties([=[prgm_exec]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/App/Tests/CMakeLists.txt;329;add_test;/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/App/Tests/CMakeLists.txt;0;")
add_test([=[normal_mode]=] "/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/build-tests/test_normal_mode")
set_tests_properties([=[normal_mode]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/App/Tests/CMakeLists.txt;330;add_test;/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/App/Tests/CMakeLists.txt;0;")
add_test([=[param]=] "/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/build-tests/test_param")
set_tests_properties([=[param]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/App/Tests/CMakeLists.txt;331;add_test;/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/App/Tests/CMakeLists.txt;0;")
add_test([=[stat]=] "/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/build-tests/test_stat")
set_tests_properties([=[stat]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/App/Tests/CMakeLists.txt;332;add_test;/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/App/Tests/CMakeLists.txt;0;")
add_test([=[yvars]=] "/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/build-tests/test_yvars")
set_tests_properties([=[yvars]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/App/Tests/CMakeLists.txt;333;add_test;/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/App/Tests/CMakeLists.txt;0;")
add_test([=[menu_state]=] "/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/build-tests/test_menu_state")
set_tests_properties([=[menu_state]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/App/Tests/CMakeLists.txt;334;add_test;/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/App/Tests/CMakeLists.txt;0;")
add_test([=[prgm_cmd_table]=] "/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/build-tests/test_prgm_cmd_table")
set_tests_properties([=[prgm_cmd_table]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/App/Tests/CMakeLists.txt;335;add_test;/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/App/Tests/CMakeLists.txt;0;")
add_test([=[parse_eval]=] "/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/build-tests/test_parse_eval")
set_tests_properties([=[parse_eval]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/App/Tests/CMakeLists.txt;336;add_test;/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/App/Tests/CMakeLists.txt;0;")
add_test([=[mode_topology]=] "/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/build-tests/test_mode_topology")
set_tests_properties([=[mode_topology]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/App/Tests/CMakeLists.txt;337;add_test;/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/App/Tests/CMakeLists.txt;0;")
add_test([=[graph_render]=] "/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/build-tests/test_graph_render")
set_tests_properties([=[graph_render]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/App/Tests/CMakeLists.txt;338;add_test;/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/App/Tests/CMakeLists.txt;0;")
add_test([=[error_codes]=] "/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/build-tests/test_error_codes")
set_tests_properties([=[error_codes]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/App/Tests/CMakeLists.txt;339;add_test;/Users/jonathanpool/STM32Projects/STM32F429-TI81-Calculator/App/Tests/CMakeLists.txt;0;")
